### ISSUE TITLE
Should this be deleted? marts/revenue_metric.sql

### ISSUE THREAD

**Issue by bbrewington** [dbt-labs/jaffle_shop_metrics#6]
This code looks like the boilerplate code here: https://docs.getdbt.com/docs/building-a-dbt-project/metrics#developing-metrics-with-metricsdevelop

Thinking it was accidentally left in the project and needs to be deleted?  Since there's an actual revenue metric at [marts/revenue.yml](https://github.com/dbt-labs/jaffle_shop_metrics/blob/main/models/marts/revenue.yml)

https://github.com/dbt-labs/jaffle_shop_metrics/blob/3c9c1cad8c2dcf4437a08285c0d6d1e190301f5a/models/marts/revenue_metric.sql#L1-L22

**Comment by callum-mcdata** [comment]
See ^ #7
